# Generated by Django 5.0b1 on 2023-12-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField(max_length=64)),
                ('emp_sal', models.FloatField()),
                ('emp_addr', models.CharField(max_length=256)),
            ],
        ),
    ]
