# Generated by Django 5.0b1 on 2023-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('id_number', models.IntegerField()),
                ('fee', models.FloatField()),
            ],
        ),
    ]
